version: "3.8"

services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - RDS_HOSTNAME=user-db
      - REDIS_URL=your-elasticache-redis-url
      - JWT_SECRET=your-secret
    depends_on:
      - user-db

  company-service:
    build: ./company-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - RDS_HOSTNAME=company-db
    depends_on:
      - company-db

  project-service:
    build: ./project-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - RDS_HOSTNAME=project-db
    depends_on:
      - project-db

  feature-service:
    build: ./feature-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - RDS_HOSTNAME=feature-db
    depends_on:
      - feature-db

  audit-service:
    build: ./audit-service
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - RDS_HOSTNAME=audit-db
    depends_on:
      - audit-db

  report-service:
    build: ./report-service
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - RDS_HOSTNAME=report-db
    depends_on:
      - report-db

  user-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: userdb
    ports:
      - "3307:3306"

  company-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: companydb
    ports:
      - "3308:3306"

  project-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: projectdb
    ports:
      - "3309:3306"

  feature-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: featuredb
    ports:
      - "3310:3306"

  audit-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auditdb
    ports:
      - "3311:3306"

  report-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reportdb
    ports:
      - "3312:3306"

  redis:
    image: redis
    ports:
      - "6379:6379"
