name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies for company-service
        working-directory: ./company-service
        run: npm install

      - name: Run tests for company-service
        working-directory: ./company-service
        run: npm test

      - name: Install dependencies for report-service
        working-directory: ./report-service
        run: npm install

      - name: Run tests for report-service
        working-directory: ./report-service
        run: npm test
